QUERY_NAME: "AGS2000"
REF_NAME: "Hilliard"
QUERY_FASTA: "/home/matthew.willman/ref/NCBI_MWillman/Taes_AGS2000_1.1.fasta"
REF_FASTA: "/home/matthew.willman/ref/NCBI_MWillman/Taes_Hilliard_1.2.fasta"
BREAKLEN: "200"    #nucmer default is 200
CHRS:
  - "chr1A"
  - "chr1B"
  - "chr1D"
  - "chr2A"
  - "chr2B"
  - "chr2D"
  - "chr3A"
  - "chr3B"
  - "chr3D"
  - "chr4A"
  - "chr4B"
  - "chr4D"
  - "chr5A"
  - "chr5B"
  - "chr5D"
  - "chr6A"
  - "chr6B"
  - "chr6D"
  - "chr7A"
  - "chr7B"
  - "chr7D"
  