QUERY_NAME: "Hilliard"
REF_NAME: "Attraktion"
QUERY_FASTA: "/90daydata/gbru_wheat2/Snakemake_reorder/Hilliard/1_Assembly/results/Hilliard.ragtag.scaffold.fa"
REF_FASTA: "/project/gbru_wheat2/ref/Attraktion_ENA/Attraktion.rename.fasta"
CHRS:
  - "chr1A"
  - "chr1B"
  - "chr1D"
  - "chr2A"
  - "chr2B"
  - "chr2D"
  - "chr3A"
  - "chr3B"
  - "chr3D"
  - "chr4A"
  - "chr4B"
  - "chr4D"
  - "chr5A"
  - "chr5B"
  - "chr5D"
  - "chr6A"
  - "chr6B"
  - "chr6D"
  - "chr7A"
  - "chr7B"
  - "chr7D"
  